In [3]:
# importo librerie utili
import pandas as pd
import math
import numpy as np
import datetime

In [6]:
# creo la lista con i nomi delle colonne
colNamesInitData_22 = ['40Ar F', 'err40Ar F', '38Ar IC0', 'err38Ar IC0', '36Ar IC1', 'err36Ar IC1','38Ar F', 'err38Ar F','36Ar IC0', 'err36Ar IC0 ', '39Ar F', 'err39Ar F', '37Ar IC0', 'err37Ar IC0' , '35Cl IC1', 'err35Cl IC1', 'gainIC0/IC1', 'err gainIC0/IC1' , '40F/36IC1',  'err 40F/36IC1',  '40F/36IC0' ,'err 40F/36IC0', 'Run', 'Path']
colnames_numeric_22 = ['40Ar F', 'err40Ar F', '38Ar IC0', 'err38Ar IC0', '36Ar IC1', 'err36Ar IC1','38Ar F', 'err38Ar F','36Ar IC0', 'err36Ar IC0 ', '39Ar F', 'err39Ar F', '37Ar IC0', 'err37Ar IC0' , '35Cl IC1', 'err35Cl IC1', 'gainIC0/IC1', 'err gainIC0/IC1' , '40F/36IC1',  'err 40F/36IC1',  '40F/36IC0' ,'err 40F/36IC0']
# definisco il percorso del file run.22
filePath_22 = "../test_data/Run22.txt"
# importo il file run.22
#df_Data = pd.read_csv(filePath, header = None, names = colNamesInitData, sep = [" ", ";"])  OKKIO TAB
df_Data_22 = pd.read_csv(filePath_22, header = None, names = colNamesInitData_22)
# qui si eliminano le graffe, ma forse si può fare in un unico passaggio all'importazione, definendo
# anche legraffe come separatori di elenco e imponendo di considerare separatori consecutivi come uno solo
# nota che ho sovrascritto il dataframe usando lo stesso nome, non serve crearne più copie che si accumulano
# in memoria
df_Data_22 = df_Data_22.replace(["{", "}"], ["", ""], regex=True)

# qui si convertono tutte le colonne del dataframe a numeric (float64), ma sicuramente si può fare
# sopra all'importazione
for i in range(len(colnames_numeric_22)):
    df_Data_22[colnames_numeric_22[i]] = pd.to_numeric(df_Data_22[colnames_numeric_22[i]])

# qui aggiungere le colonne "mancanti"

# qui si visualizza il dataframe importato e pulito
df_Data_22

# va ripetuto per file run.4 e triplo36 -> df_Data_4 df_Data_36

# poi i tre dataframe devono essere concatenati a darne uno nuovo con tutte le colonne
# come esempio df_Data = pd.concat([df_Data_22, df_Data_4, df_Data_36], axis = 0)  -- asse 0 = righe

# riga temporanea per evitare errori sotto
df_Data = df_Data_22
df_Data

,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,36Ar IC0,err36Ar IC0,...,35Cl IC1,err35Cl IC1,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err 40F/36IC1,40F/36IC0,err 40F/36IC0,Run,Path
0,7.416700,0.002500,0.001269,6.900000e-07,0.001755,3.000000e-06,0.000694,0.000016,0.002021,9.200000e-07,...,0.000013,6.400000e-08,1.151210,0.0021,4225.330,7.50,3670.350,2.10,'PHALABORWA STP4' run on 19 May 2015 at 13:32,Raw data stored in - C:\Nu Noble\Results\Data...
1,6.614000,0.002300,0.001036,6.900000e-07,0.001198,2.100000e-06,0.000668,0.000016,0.001411,7.400000e-07,...,0.000012,6.300000e-08,1.177690,0.0021,5519.020,9.80,4686.290,2.90,'PHALABORWA STP5' run on 19 May 2015 at 13:55,Raw data stored in - C:\Nu Noble\Results\Data...
2,9.369080,0.003800,0.001380,7.100000e-07,0.001129,1.700000e-06,0.000993,0.000020,0.001330,6.900000e-07,...,0.000013,6.700000e-08,1.178730,0.0019,8300.450,13.00,7041.880,4.60,'PHALABORWA STP6' run on 19 May 2015 at 14:19,Raw data stored in - C:\Nu Noble\Results\Data...
3,8.058740,0.003000,0.001139,6.800000e-07,0.000528,7.100000e-07,0.000906,0.000020,0.000660,4.400000e-07,...,0.000013,5.400000e-08,1.250590,0.0019,15268.100,21.00,12208.700,9.40,'PHALABORWA STP8' run on 19 May 2015 at 15:12,Raw data stored in - C:\Nu Noble\Results\Data...
4,11.968100,0.004600,0.001673,1.000000e-06,0.000496,7.000000e-07,0.001193,0.000026,0.000620,5.200000e-07,...,0.000013,6.500000e-08,1.249520,0.0020,24117.300,35.00,19301.300,18.00,'PHALABORWA STP9' run on 19 May 2015 at 15:37,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,0.426141,0.000120,0.003709,2.600000e-06,0.000883,7.200000e-07,0.004290,0.000017,0.000881,8.000000e-07,...,0.000018,1.100000e-07,0.997925,0.0012,482.535,0.42,483.538,0.46,'BAL-T12 LG ST2' run on 23 June 2020 at 15:31,Raw data stored in - C:\Nu Noble\Results\Data...
1334,0.224427,0.000066,0.003784,2.800000e-06,0.000268,4.000000e-07,0.004378,0.000017,0.000268,4.100000e-07,...,0.000018,1.100000e-07,1.003020,0.0022,838.663,1.30,836.139,1.30,'BAL-T12 LG ST3' run on 23 June 2020 at 15:57,Raw data stored in - C:\Nu Noble\Results\Data...
1335,0.421204,0.000130,0.004853,3.600000e-06,0.000743,7.200000e-07,0.005579,0.000016,0.000749,6.800000e-07,...,0.000018,1.000000e-07,1.008230,0.0013,567.014,0.58,562.386,0.54,'BAL-T12 LG ST6' run on 23 June 2020 at 17:08,Raw data stored in - C:\Nu Noble\Results\Data...
1336,0.585912,0.000160,0.011360,1.100000e-05,0.000572,6.300000e-07,0.012936,0.000016,0.000581,6.800000e-07,...,0.000019,1.100000e-07,1.015770,0.0016,1024.300,1.20,1008.400,1.20,'BAL-T12 ST7' run on 23 June 2020 at 17:26,Raw data stored in - C:\Nu Noble\Results\Data...
1337,0.605563,0.000170,0.012759,1.100000e-05,0.000492,7.100000e-07,0.014504,0.000017,0.000503,5.500000e-07,...,0.000019,1.300000e-07,1.021820,0.0018,1230.700,1.80,1204.420,1.40,'Sample Name' run on 23 June 2020 at 17:54,Raw data stored in - C:\Nu Noble\Results\Data...

In [3]:
# qui si splitta la colonna 'Run' in due colonne con none del run e data/ora
run_split = df_Data['Run'].str.split(" run on ")

# qui di formatta la colonna con nome del run (una Pandas SERIES) e le si da un nome
run_name = run_split.str[0]
run_name = run_name.replace(["'"], [""], regex=True)
run_name.name = 'Run_Name'

# idem per data, inoltre si converte il tipo in datetime64
dataora = run_split.str[1]
dataora.name = 'Date_Time'
dataora = pd.to_datetime(dataora)

# print(dataora.values)
# print(dataora.values[0])
# print(type(dataora.values[0]))
# print(dir(dataora.values[0]))

# qui si concatenano le nuove serie all'inizio del datframe con dati
df_Data = pd.concat([run_name, dataora, df_Data], axis = 1)

# qui si elimina la colonna non più usata
df_Data.drop('Run',axis=1, inplace=True)

# qui si visualizza il dataframe con le due nuove colonne
df_Data

,Run_Name,Date_Time,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,...,err37Ar IC0,35Cl IC1,err35Cl IC1,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err 40F/36IC1,40F/36IC0,err 40F/36IC0,Path
0,PHALABORWA STP4,2015-05-19 13:32:00,7.416700,0.002500,0.001269,6.900000e-07,0.001755,3.000000e-06,0.000694,0.000016,...,4.900000e-08,0.000013,6.400000e-08,1.151210,0.0021,4225.330,7.50,3670.350,2.10,Raw data stored in - C:\Nu Noble\Results\Data...
1,PHALABORWA STP5,2015-05-19 13:55:00,6.614000,0.002300,0.001036,6.900000e-07,0.001198,2.100000e-06,0.000668,0.000016,...,5.100000e-08,0.000012,6.300000e-08,1.177690,0.0021,5519.020,9.80,4686.290,2.90,Raw data stored in - C:\Nu Noble\Results\Data...
2,PHALABORWA STP6,2015-05-19 14:19:00,9.369080,0.003800,0.001380,7.100000e-07,0.001129,1.700000e-06,0.000993,0.000020,...,5.200000e-08,0.000013,6.700000e-08,1.178730,0.0019,8300.450,13.00,7041.880,4.60,Raw data stored in - C:\Nu Noble\Results\Data...
3,PHALABORWA STP8,2015-05-19 15:12:00,8.058740,0.003000,0.001139,6.800000e-07,0.000528,7.100000e-07,0.000906,0.000020,...,5.000000e-08,0.000013,5.400000e-08,1.250590,0.0019,15268.100,21.00,12208.700,9.40,Raw data stored in - C:\Nu Noble\Results\Data...
4,PHALABORWA STP9,2015-05-19 15:37:00,11.968100,0.004600,0.001673,1.000000e-06,0.000496,7.000000e-07,0.001193,0.000026,...,5.600000e-08,0.000013,6.500000e-08,1.249520,0.0020,24117.300,35.00,19301.300,18.00,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,BAL-T12 LG ST2,2020-06-23 15:31:00,0.426141,0.000120,0.003709,2.600000e-06,0.000883,7.200000e-07,0.004290,0.000017,...,9.300000e-08,0.000018,1.100000e-07,0.997925,0.0012,482.535,0.42,483.538,0.46,Raw data stored in - C:\Nu Noble\Results\Data...
1334,BAL-T12 LG ST3,2020-06-23 15:57:00,0.224427,0.000066,0.003784,2.800000e-06,0.000268,4.000000e-07,0.004378,0.000017,...,7.600000e-08,0.000018,1.100000e-07,1.003020,0.0022,838.663,1.30,836.139,1.30,Raw data stored in - C:\Nu Noble\Results\Data...
1335,BAL-T12 LG ST6,2020-06-23 17:08:00,0.421204,0.000130,0.004853,3.600000e-06,0.000743,7.200000e-07,0.005579,0.000016,...,9.200000e-08,0.000018,1.000000e-07,1.008230,0.0013,567.014,0.58,562.386,0.54,Raw data stored in - C:\Nu Noble\Results\Data...
1336,BAL-T12 ST7,2020-06-23 17:26:00,0.585912,0.000160,0.011360,1.100000e-05,0.000572,6.300000e-07,0.012936,0.000016,...,7.800000e-08,0.000019,1.100000e-07,1.015770,0.0016,1024.300,1.20,1008.400,1.20,Raw data stored in - C:\Nu Noble\Results\Data...
1337,Sample Name,2020-06-23 17:54:00,0.605563,0.000170,0.012759,1.100000e-05,0.000492,7.100000e-07,0.014504,0.000017,...,7.900000e-08,0.000019,1.300000e-07,1.021820,0.0018,1230.700,1.80,1204.420,1.40,Raw data stored in - C:\Nu Noble\Results\Data...

In [4]:
# esempio di filtro in base alla data

# data in base a cui filtro
value_to_check = pd.Timestamp(2020, 6, 23)


# applico il filtro
df_Data_filtered = df_Data[df_Data['Date_Time'] > value_to_check]

df_Data_filtered

,Run_Name,Date_Time,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,...,err37Ar IC0,35Cl IC1,err35Cl IC1,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err 40F/36IC1,40F/36IC0,err 40F/36IC0,Path
1332,BAL-T12 SM ST5,2020-06-23 13:38:00,0.440568,0.000120,0.005370,0.000004,0.000776,7.700000e-07,0.006207,0.000016,...,6.500000e-08,0.000018,1.100000e-07,1.006620,0.0013,567.880,0.58,564.147,0.52,Raw data stored in - C:\Nu Noble\Results\Data...
1333,BAL-T12 LG ST2,2020-06-23 15:31:00,0.426141,0.000120,0.003709,0.000003,0.000883,7.200000e-07,0.004290,0.000017,...,9.300000e-08,0.000018,1.100000e-07,0.997925,0.0012,482.535,0.42,483.538,0.46,Raw data stored in - C:\Nu Noble\Results\Data...
1334,BAL-T12 LG ST3,2020-06-23 15:57:00,0.224427,0.000066,0.003784,0.000003,0.000268,4.000000e-07,0.004378,0.000017,...,7.600000e-08,0.000018,1.100000e-07,1.003020,0.0022,838.663,1.30,836.139,1.30,Raw data stored in - C:\Nu Noble\Results\Data...
1335,BAL-T12 LG ST6,2020-06-23 17:08:00,0.421204,0.000130,0.004853,0.000004,0.000743,7.200000e-07,0.005579,0.000016,...,9.200000e-08,0.000018,1.000000e-07,1.008230,0.0013,567.014,0.58,562.386,0.54,Raw data stored in - C:\Nu Noble\Results\Data...
1336,BAL-T12 ST7,2020-06-23 17:26:00,0.585912,0.000160,0.011360,0.000011,0.000572,6.300000e-07,0.012936,0.000016,...,7.800000e-08,0.000019,1.100000e-07,1.015770,0.0016,1024.300,1.20,1008.400,1.20,Raw data stored in - C:\Nu Noble\Results\Data...
1337,Sample Name,2020-06-23 17:54:00,0.605563,0.000170,0.012759,0.000011,0.000492,7.100000e-07,0.014504,0.000017,...,7.900000e-08,0.000019,1.300000e-07,1.021820,0.0018,1230.700,1.80,1204.420,1.40,Raw data stored in - C:\Nu Noble\Results\Data...

In [5]:
# esempio di filtro in base alla data

# date in base a cui filtro
value_min = pd.Timestamp(year=2020, month=6, day=22, hour=14)
value_max = pd.Timestamp(year=2020, month=6, day=23, hour=0)


# applico il filtro
df_Data_filtered = df_Data[(df_Data['Date_Time'] > value_min) & (df_Data['Date_Time'] < value_max)]

df_Data_filtered

,Run_Name,Date_Time,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,...,err37Ar IC0,35Cl IC1,err35Cl IC1,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err 40F/36IC1,40F/36IC0,err 40F/36IC0,Path
1330,MH-T4 ST9,2020-06-22 15:52:00,0.574987,0.00018,0.007327,0.000006,0.000894,1.000000e-06,0.008469,0.000019,...,7.600000e-08,0.000018,1.200000e-07,1.006970,0.0014,643.104,0.75,638.656,0.56,Raw data stored in - C:\Nu Noble\Results\Data...
1331,MH-T4 ST10,2020-06-22 16:15:00,0.380150,0.00011,0.003130,0.000002,0.000867,8.600000e-07,0.003649,0.000015,...,7.400000e-08,0.000018,1.100000e-07,0.991297,0.0015,438.573,0.45,442.423,0.51,Raw data stored in - C:\Nu Noble\Results\Data...