# PyCalcolAr: questo e il file finale con tutte le operazioni insieme

In [53]:

#imports
import pandas as pd
import numpy as np
import math 

from IPython.display import display

Inizio importanto il file Triplo 36 (che per ora terrò separato dagli altri dataframe di dati Run4 e Run22)

In [54]:
delay = 246

columns_names=['40F', 'err 40F', '38IC0', 'err 38IC0', '36IC1', 'err 36IC1', '36IC0', 'err 36IC0','36F', 'err 36F', 'gain IC0/IC1', 'err gain IC0/IC1', 'gain F/IC1', 'err gain F/IC1' , 'gain F/IC0', 'err gain F/IC0', '40F/36IC1', 'err 40F/36IC1 ', '40F/36F', 'err 40F/36F', '40F/36IC0', 'err 40F/36IC0' , '38IC0/36IC0', 'err 38IC0/36IC0', 'Run', 'Path']
file_path = "../test_data/Triplo36.txt"
airpipette_data = pd.read_csv(file_path, header = None, names = columns_names, sep = '\t|,', engine = 'python')  # abbiamo usato come separatore
                                                                                                    #entrambi i caratteri ',' (virgola) 
                                                                                                    #e '\t' (tab)

#si eliminano i charatteri "{}" dalle colonne relative all'errore
airpipette_data = airpipette_data.replace(["{", "}"], ["", ""], regex=True)

#tengo solo le colonne di interesse
airpipette_data = airpipette_data[['40F', 'err 40F', '38IC0', 'err 38IC0', '36IC1', 'err 36IC1', '36IC0', 'err 36IC0','36F', 'err 36F', 'Run', 'Path']]


print("Air pipette initial imported data:")
display(airpipette_data)

Air pipette initial imported data:

,40F,err 40F,38IC0,err 38IC0,36IC1,err 36IC1,36IC0,err 36IC0,36F,err 36F,Run,Path
0,0.73900,4.0e-03,49900.0,5.8e+01,72000.0,2.3e+02,259000.0,1.6e+02,144000.0,1.3e+03,'Sample Name' run on 06 October 2015 at 10:33,Raw data stored in - C:\Nu Noble\Results\Data...
1,1.22000,4.1e-04,49700.0,6.0e+01,75600.0,2.0e+02,258000.0,1.6e+02,251000.0,8.7e+02,'Sample Name' run on 06 October 2015 at 10:52,Raw data stored in - C:\Nu Noble\Results\Data...
2,1.22000,5.1e-04,49800.0,5.1e+01,76800.0,1.9e+02,259000.0,1.5e+02,251000.0,9.1e+02,'Sample Name' run on 06 October 2015 at 11:23,Raw data stored in - C:\Nu Noble\Results\Data...
3,0.75800,4.0e-03,49700.0,5.5e+01,66600.0,2.3e+02,258000.0,1.4e+02,144000.0,1.1e+03,'Sample Name' run on 08 October 2015 at 10:13,Raw data stored in - C:\Nu Noble\Results\Data...
4,1.09000,3.6e-04,43300.0,6.3e+01,60800.0,1.7e+02,224000.0,1.3e+02,220000.0,1.4e+03,'Sample Name' run on 08 October 2015 at 10:27,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...
829,1.65538,5.3e-04,55318.2,7.9e+01,307546.0,2.5e+02,298052.0,2.4e+02,347513.0,1.1e+03,'Sample Name' run on 23 June 2020 at 11:02,Raw data stored in - C:\Nu Noble\Results\Data...
830,1.65331,4.3e-04,55167.7,9.0e+01,305585.0,2.2e+02,297394.0,3.0e+02,349141.0,1.3e+03,'Sample Name' run on 24 June 2020 at 09:25,Raw data stored in - C:\Nu Noble\Results\Data...
831,1.65039,4.9e-04,55606.8,8.2e+01,306701.0,2.0e+02,299474.0,2.6e+02,347983.0,1.3e+03,'Sample Name' run on 24 June 2020 at 09:50,Raw data stored in - C:\Nu Noble\Results\Data...
832,1.64847,5.6e-04,55592.8,6.3e+01,306848.0,2.6e+02,299066.0,2.3e+02,346598.0,1.4e+03,'Sample Name' run on 24 June 2020 at 10:08,Raw data stored in - C:\Nu Noble\Results\Data...
833,1.65661,4.7e-04,54386.0,8.5e+01,305470.0,2.8e+02,293720.0,3.3e+02,346964.0,1.2e+03,'Sample Name' run on 29 June 2020 at 09:41,Raw data stored in - C:\Nu Noble\Results\Data...

Il dataframe deve essere filtrato per data, per scegliere la riga di calibrazione d'interesse

In [55]:
# qui si splitta la colonna 'Run' in due colonne con nome del run e data/ora
run_split = airpipette_data['Run'].str.split(" run on ")

In [56]:
# qui di formatta la colonna con nome del run (una Pandas SERIES) e le si da un nome
run_name = run_split.str[0]
run_name = run_name.replace(["'"], [""], regex=True)
run_name.name = 'Run_Name'

In [57]:
# idem per data, inoltre si converte il tipo in datetime64
dataora = run_split.str[1]
dataora.name = 'Date_Time'
dataora = pd.to_datetime(dataora)

In [58]:
# qui si concatenano le nuove serie all'inizio del datframe con dati
airpipette_data = pd.concat([run_name, dataora, airpipette_data], axis = 1)

In [59]:
# qui si elimina la colonna non più usata
airpipette_data.drop('Run',axis=1, inplace=True)
display(airpipette_data)

,Run_Name,Date_Time,40F,err 40F,38IC0,err 38IC0,36IC1,err 36IC1,36IC0,err 36IC0,36F,err 36F,Path
0,Sample Name,2015-10-06 10:33:00,0.73900,4.0e-03,49900.0,5.8e+01,72000.0,2.3e+02,259000.0,1.6e+02,144000.0,1.3e+03,Raw data stored in - C:\Nu Noble\Results\Data...
1,Sample Name,2015-10-06 10:52:00,1.22000,4.1e-04,49700.0,6.0e+01,75600.0,2.0e+02,258000.0,1.6e+02,251000.0,8.7e+02,Raw data stored in - C:\Nu Noble\Results\Data...
2,Sample Name,2015-10-06 11:23:00,1.22000,5.1e-04,49800.0,5.1e+01,76800.0,1.9e+02,259000.0,1.5e+02,251000.0,9.1e+02,Raw data stored in - C:\Nu Noble\Results\Data...
3,Sample Name,2015-10-08 10:13:00,0.75800,4.0e-03,49700.0,5.5e+01,66600.0,2.3e+02,258000.0,1.4e+02,144000.0,1.1e+03,Raw data stored in - C:\Nu Noble\Results\Data...
4,Sample Name,2015-10-08 10:27:00,1.09000,3.6e-04,43300.0,6.3e+01,60800.0,1.7e+02,224000.0,1.3e+02,220000.0,1.4e+03,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
829,Sample Name,2020-06-23 11:02:00,1.65538,5.3e-04,55318.2,7.9e+01,307546.0,2.5e+02,298052.0,2.4e+02,347513.0,1.1e+03,Raw data stored in - C:\Nu Noble\Results\Data...
830,Sample Name,2020-06-24 09:25:00,1.65331,4.3e-04,55167.7,9.0e+01,305585.0,2.2e+02,297394.0,3.0e+02,349141.0,1.3e+03,Raw data stored in - C:\Nu Noble\Results\Data...
831,Sample Name,2020-06-24 09:50:00,1.65039,4.9e-04,55606.8,8.2e+01,306701.0,2.0e+02,299474.0,2.6e+02,347983.0,1.3e+03,Raw data stored in - C:\Nu Noble\Results\Data...
832,Sample Name,2020-06-24 10:08:00,1.64847,5.6e-04,55592.8,6.3e+01,306848.0,2.6e+02,299066.0,2.3e+02,346598.0,1.4e+03,Raw data stored in - C:\Nu Noble\Results\Data...
833,Sample Name,2020-06-29 09:41:00,1.65661,4.7e-04,54386.0,8.5e+01,305470.0,2.8e+02,293720.0,3.3e+02,346964.0,1.2e+03,Raw data stored in - C:\Nu Noble\Results\Data...

In [60]:
#qui si filtra il dataframe per data, prendendo una sola riga del dataframe 
filter_calibration_min_data = pd.Timestamp(year=2020, month=6, day=23, hour=10)
filter_calibration_max_data = pd.Timestamp(year=2020, month=6, day=23, hour=10, minute = 30)

airpipette_data_filtered = airpipette_data[(airpipette_data['Date_Time'] > filter_calibration_min_data) & \
                                           (airpipette_data['Date_Time'] < filter_calibration_max_data)]

airpipette_data_filtered

,Run_Name,Date_Time,40F,err 40F,38IC0,err 38IC0,36IC1,err 36IC1,36IC0,err 36IC0,36F,err 36F,Path
827,Sample Name,2020-06-23 10:06:00,1.65404,4.4e-04,54937.6,8.0e+01,305230.0,2.5e+02,295763.0,3.1e+02,346234.0,1.0e+03,Raw data stored in - C:\Nu Noble\Results\Data...

In [61]:
#qui si fa il check per assicurarsi che il risultato contenga una sola riga, 
#altrimenti si stamperà un messago di errore 

if len(airpipette_data_filtered.index) == 1:
    calibration_data = airpipette_data_filtered  
else:   
    print("Error of calibration file filter. The limits set by the user gives more than one measure result. Please modify the data limits")


Ora che abbiamo importato i dati di calibrazione correttamente, faremo la stessa operazione con i file di misure run4 e run 22.

### Importazione file dati (Run 4 e Run22)

In [62]:
# creo la lista con i nomi delle colonne
column_names_run4 = ['40Ar F', 'err40Ar F', '38Ar IC0', 'err38Ar IC0', '36Ar IC1', 'err36Ar IC1','38Ar F', 'err38Ar F','36Ar IC0', 'err36Ar IC0', '39Ar F', 'err39Ar F', '37Ar IC0', 'err37Ar IC0' , '35Cl IC1', 'err35Cl IC1', '39Ar IC0',  'err39Ar IC0',  '37Ar IC1', 'err37Ar IC1', 'gainF/IC0', 'err gainF/IC0' , 'gainIC0/IC1', 'err gainIC0/IC1', '40F/36IC1',  'err40F/36IC1',  '40F/36IC0' ,'err40F/36IC0', 'Run', 'Path']
column_names_run22 = ['40Ar F', 'err40Ar F', '38Ar IC0', 'err38Ar IC0', '36Ar IC1', 'err36Ar IC1','38Ar F', 'err38Ar F','36Ar IC0', 'err36Ar IC0', '39Ar F', 'err39Ar F', '37Ar IC0', 'err37Ar IC0' , '35Cl IC1', 'err35Cl IC1', 'gainIC0/IC1', 'err gainIC0/IC1' , '40F/36IC1',  'err40F/36IC1',  '40F/36IC0' ,'err40F/36IC0', 'Run', 'Path']

# definisco il percorso dei file
file_path_4 = "../test_data/Run4.txt"
file_path_22 = "../test_data/Run22.txt"

# importo i file run
df_data_4 = pd.read_csv(file_path_4, header = None, index_col= False, names = column_names_run4, sep = '\t|,', engine = 'python')
df_data_22 = pd.read_csv(file_path_22, header = None, index_col= False, names = column_names_run22, sep = '\t|,', engine = 'python')

In [63]:
#cancellare certi caratteri dalle colonne perpoter transformali in valori numerici
df_data_4 = df_data_4.replace(["{", "}"], ["", ""], regex=True)
df_data_22 = df_data_22.replace(["{", "}"], ["", ""], regex=True)

In [64]:
#definire nome delle colonne che contengono dati numerici
colnames_numeric_4 = ['40Ar F', 'err40Ar F', '38Ar IC0', 'err38Ar IC0', '36Ar IC1', 'err36Ar IC1','38Ar F', 'err38Ar F','36Ar IC0', 'err36Ar IC0', '39Ar F', 'err39Ar F', '37Ar IC0', 'err37Ar IC0' , '35Cl IC1', 'err35Cl IC1', '39Ar IC0',  'err39Ar IC0',  '37Ar IC1', 'err37Ar IC1', 'gainF/IC0', 'err gainF/IC0' , 'gainIC0/IC1', 'err gainIC0/IC1', '40F/36IC1',  'err40F/36IC1',  '40F/36IC0' ,'err40F/36IC0']   
colnames_numeric_22 = ['40Ar F', 'err40Ar F', '38Ar IC0', 'err38Ar IC0', '36Ar IC1', 'err36Ar IC1','38Ar F', 'err38Ar F','36Ar IC0', 'err36Ar IC0', '39Ar F', 'err39Ar F', '37Ar IC0', 'err37Ar IC0' , '35Cl IC1', 'err35Cl IC1', 'gainIC0/IC1', 'err gainIC0/IC1' , '40F/36IC1',  'err40F/36IC1',  '40F/36IC0' ,'err40F/36IC0']

# si convertono tutte le colonne del dataframe a numeric (float64)
for i in colnames_numeric_4:
    df_data_4[i] = pd.to_numeric(df_data_4[i])

# si convertono tutte le colonne del dataframe a numeric (float64)
for i in colnames_numeric_22:
    df_data_22[i] = pd.to_numeric(df_data_22[i])

Dopo aver importato tutti e due i file di dati come dataframe, verranno messi in sieme in un unico dataframe di dati

In [65]:
df_data = pd.concat([df_data_4, df_data_22], axis=0)
display(df_data)

,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,36Ar IC0,err36Ar IC0,...,gainF/IC0,err gainF/IC0,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err40F/36IC1,40F/36IC0,err40F/36IC0,Run,Path
0,0.847000,0.000370,0.000493,3.700000e-07,0.002460,3.900000e-06,0.000047,0.000015,0.002610,1.300000e-06,...,0.396,0.064,1.060000,0.0018,345.000,0.57,325.000,0.21,'fishcanyon bt stp1' run on 08 April 2015 at 1...,Raw data stored in - C:\Nu Noble\Results\Data...
1,2.300000,0.000870,0.001540,8.500000e-07,0.006340,9.200000e-06,0.000107,0.000013,0.006510,2.500000e-06,...,2.670,0.018,1.030000,0.0015,363.000,0.55,354.000,0.19,'fishcanyon bt stp2' run on 08 April 2015 at 1...,Raw data stored in - C:\Nu Noble\Results\Data...
2,1.080000,0.000350,0.000750,5.000000e-07,0.002850,5.400000e-06,0.000037,0.000012,0.003050,1.400000e-06,...,4.340,0.029,1.070000,0.0021,378.000,0.72,354.000,0.20,'Sample Name' run on 08 April 2015 at 17:28,Raw data stored in - C:\Nu Noble\Results\Data...
3,0.089300,0.000040,0.000059,1.300000e-07,0.000215,2.700000e-07,0.000009,0.000012,0.000259,2.900000e-07,...,2.160,0.260,1.210000,0.0020,416.000,0.55,345.000,0.41,'Sample Name' run on 09 April 2015 at 11:39,Raw data stored in - C:\Nu Noble\Results\Data...
4,0.578000,0.000270,0.000329,3.000000e-07,0.001530,2.400000e-06,0.000050,0.000011,0.001700,8.900000e-07,...,48700.000,48000.000,1.110000,0.0018,378.000,0.61,340.000,0.24,'Sample Name' run on 09 April 2015 at 12:11,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,0.426141,0.000120,0.003709,2.600000e-06,0.000883,7.200000e-07,0.004290,0.000017,0.000881,8.000000e-07,...,NaN,NaN,0.997925,0.0012,482.535,0.42,483.538,0.46,'BAL-T12 LG ST2' run on 23 June 2020 at 15:31,Raw data stored in - C:\Nu Noble\Results\Data...
1334,0.224427,0.000066,0.003784,2.800000e-06,0.000268,4.000000e-07,0.004378,0.000017,0.000268,4.100000e-07,...,NaN,NaN,1.003020,0.0022,838.663,1.30,836.139,1.30,'BAL-T12 LG ST3' run on 23 June 2020 at 15:57,Raw data stored in - C:\Nu Noble\Results\Data...
1335,0.421204,0.000130,0.004853,3.600000e-06,0.000743,7.200000e-07,0.005579,0.000016,0.000749,6.800000e-07,...,NaN,NaN,1.008230,0.0013,567.014,0.58,562.386,0.54,'BAL-T12 LG ST6' run on 23 June 2020 at 17:08,Raw data stored in - C:\Nu Noble\Results\Data...
1336,0.585912,0.000160,0.011360,1.100000e-05,0.000572,6.300000e-07,0.012936,0.000016,0.000581,6.800000e-07,...,NaN,NaN,1.015770,0.0016,1024.300,1.20,1008.400,1.20,'BAL-T12 ST7' run on 23 June 2020 at 17:26,Raw data stored in - C:\Nu Noble\Results\Data...
1337,0.605563,0.000170,0.012759,1.100000e-05,0.000492,7.100000e-07,0.014504,0.000017,0.000503,5.500000e-07,...,NaN,NaN,1.021820,0.0018,1230.700,1.80,1204.420,1.40,'Sample Name' run on 23 June 2020 at 17:54,Raw data stored in - C:\Nu Noble\Results\Data...

Ottenere run name e data per ogni riga come si faceva per Triplo36

In [66]:
# qui si splitta la colonna 'Run' in due colonne con nome del run e data/ora
run_split = df_data['Run'].str.split(" run on ")
# qui di formatta la colonna con nome del run (una Pandas SERIES) e le si da un nome
run_name = run_split.str[0]
run_name = run_name.replace(["'"], [""], regex=True)
run_name.name = 'Run_Name'
# idem per data, inoltre si converte il tipo in datetime64
dataora = run_split.str[1]
dataora.name = 'Date_Time'
dataora = pd.to_datetime(dataora)
# qui si concatenano le nuove serie all'inizio del datframe con dati
df_data = pd.concat([run_name, dataora, df_data], axis = 1)
# qui si elimina la colonna non più usata
df_data.drop('Run',axis=1, inplace=True)
display(df_data)

,Run_Name,Date_Time,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,...,err37Ar IC1,gainF/IC0,err gainF/IC0,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err40F/36IC1,40F/36IC0,err40F/36IC0,Path
0,fishcanyon bt stp1,2015-04-08 16:03:00,0.847000,0.000370,0.000493,3.700000e-07,0.002460,3.900000e-06,0.000047,0.000015,...,6.600000e-09,0.396,0.064,1.060000,0.0018,345.000,0.57,325.000,0.21,Raw data stored in - C:\Nu Noble\Results\Data...
1,fishcanyon bt stp2,2015-04-08 16:33:00,2.300000,0.000870,0.001540,8.500000e-07,0.006340,9.200000e-06,0.000107,0.000013,...,1.000000e-08,2.670,0.018,1.030000,0.0015,363.000,0.55,354.000,0.19,Raw data stored in - C:\Nu Noble\Results\Data...
2,Sample Name,2015-04-08 17:28:00,1.080000,0.000350,0.000750,5.000000e-07,0.002850,5.400000e-06,0.000037,0.000012,...,8.200000e-09,4.340,0.029,1.070000,0.0021,378.000,0.72,354.000,0.20,Raw data stored in - C:\Nu Noble\Results\Data...
3,Sample Name,2015-04-09 11:39:00,0.089300,0.000040,0.000059,1.300000e-07,0.000215,2.700000e-07,0.000009,0.000012,...,4.400000e-08,2.160,0.260,1.210000,0.0020,416.000,0.55,345.000,0.41,Raw data stored in - C:\Nu Noble\Results\Data...
4,Sample Name,2015-04-09 12:11:00,0.578000,0.000270,0.000329,3.000000e-07,0.001530,2.400000e-06,0.000050,0.000011,...,6.400000e-09,48700.000,48000.000,1.110000,0.0018,378.000,0.61,340.000,0.24,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,BAL-T12 LG ST2,2020-06-23 15:31:00,0.426141,0.000120,0.003709,2.600000e-06,0.000883,7.200000e-07,0.004290,0.000017,...,NaN,NaN,NaN,0.997925,0.0012,482.535,0.42,483.538,0.46,Raw data stored in - C:\Nu Noble\Results\Data...
1334,BAL-T12 LG ST3,2020-06-23 15:57:00,0.224427,0.000066,0.003784,2.800000e-06,0.000268,4.000000e-07,0.004378,0.000017,...,NaN,NaN,NaN,1.003020,0.0022,838.663,1.30,836.139,1.30,Raw data stored in - C:\Nu Noble\Results\Data...
1335,BAL-T12 LG ST6,2020-06-23 17:08:00,0.421204,0.000130,0.004853,3.600000e-06,0.000743,7.200000e-07,0.005579,0.000016,...,NaN,NaN,NaN,1.008230,0.0013,567.014,0.58,562.386,0.54,Raw data stored in - C:\Nu Noble\Results\Data...
1336,BAL-T12 ST7,2020-06-23 17:26:00,0.585912,0.000160,0.011360,1.100000e-05,0.000572,6.300000e-07,0.012936,0.000016,...,NaN,NaN,NaN,1.015770,0.0016,1024.300,1.20,1008.400,1.20,Raw data stored in - C:\Nu Noble\Results\Data...
1337,Sample Name,2020-06-23 17:54:00,0.605563,0.000170,0.012759,1.100000e-05,0.000492,7.100000e-07,0.014504,0.000017,...,NaN,NaN,NaN,1.021820,0.0018,1230.700,1.80,1204.420,1.40,Raw data stored in - C:\Nu Noble\Results\Data...

Filtrare set di dati per data

In [67]:
#qui si filtra il dataframe per data, prendendo una sola riga del dataframe 
filter_data_min = pd.Timestamp(year=2020, month=6, day=23, hour=10)
filter_data_max = pd.Timestamp(year=2020, month=6, day=26, hour=0)

df_data = df_data[(df_data['Date_Time'] > filter_data_min) & \
                                           (df_data['Date_Time'] < filter_data_max)]
df_data.reset_index(drop=True, inplace=True)
display(df_data)

,Run_Name,Date_Time,40Ar F,err40Ar F,38Ar IC0,err38Ar IC0,36Ar IC1,err36Ar IC1,38Ar F,err38Ar F,...,err37Ar IC1,gainF/IC0,err gainF/IC0,gainIC0/IC1,err gainIC0/IC1,40F/36IC1,err40F/36IC1,40F/36IC0,err40F/36IC0,Path
0,BAL-T12 SM ST1,2020-06-23 12:02:00,0.277142,0.000093,0.000348,5.200000e-07,0.000792,7.300000e-07,0.000382,0.000017,...,6.600000e-08,1.19585,0.0120,0.972248,0.00130,350.099,0.34,360.092,0.39,Raw data stored in - C:\Nu Noble\Results\Data...
1,BAL-T12 SM ST2,2020-06-23 12:27:00,0.516114,0.000160,0.001671,1.000000e-06,0.001361,8.500000e-07,0.001929,0.000014,...,8.700000e-08,1.16794,0.0015,0.990284,0.00098,379.123,0.26,382.843,0.32,Raw data stored in - C:\Nu Noble\Results\Data...
2,BAL-T12 SM ST3,2020-06-23 12:48:00,0.134762,0.000038,0.001201,8.600000e-07,0.000280,4.200000e-07,0.001408,0.000014,...,8.100000e-08,1.16792,0.0017,0.998740,0.00200,482.110,0.73,482.718,0.69,Raw data stored in - C:\Nu Noble\Results\Data...
3,BAL-T12 AM ST4,2020-06-23 13:15:00,0.177961,0.000059,0.001600,1.000000e-06,0.000371,4.100000e-07,0.001839,0.000014,...,7.900000e-08,1.15714,0.0015,1.002560,0.00160,479.553,0.55,478.329,0.57,Raw data stored in - C:\Nu Noble\Results\Data...
4,BAL-T12 LG ST1,2020-06-23 15:10:00,0.963265,0.000270,0.001579,9.300000e-07,0.002737,1.500000e-06,0.001843,0.000017,...,8.700000e-08,1.16399,0.0023,0.991731,0.00079,351.999,0.22,354.934,0.22,Raw data stored in - C:\Nu Noble\Results\Data...
5,BAL-T12 LG ST4,2020-06-23 16:22:00,0.133250,0.000043,0.001844,1.100000e-06,0.000203,3.200000e-07,0.002098,0.000015,...,1.000000e-07,1.15380,0.0013,1.016020,0.00240,657.881,1.10,647.505,1.10,Raw data stored in - C:\Nu Noble\Results\Data...
6,BAL-T12 LG ST5,2020-06-23 16:47:00,0.164828,0.000057,0.001638,9.400000e-07,0.000318,4.000000e-07,0.001869,0.000015,...,8.600000e-08,1.15406,0.0016,1.019070,0.00180,518.678,0.67,508.972,0.63,Raw data stored in - C:\Nu Noble\Results\Data...
7,BAL-T12 lg ST10,2020-06-23 18:22:00,0.224257,0.000075,0.001276,8.000000e-07,0.000568,5.300000e-07,0.001460,0.000015,...,8.100000e-08,1.14821,0.0016,1.008540,0.00150,395.092,0.39,391.748,0.45,Raw data stored in - C:\Nu Noble\Results\Data...
8,TOM SM ST1,2020-06-24 11:19:00,0.143381,0.000050,0.000129,2.500000e-07,0.000410,4.800000e-07,0.000205,0.000018,...,5.600000e-08,1.45045,0.1300,0.960810,0.00160,349.708,0.43,363.972,0.45,Raw data stored in - C:\Nu Noble\Results\Data...
9,Sample Name,2020-06-24 11:47:00,0.646386,0.000210,0.000391,4.200000e-07,0.001882,1.300000e-06,0.000501,0.000016,...,6.800000e-08,1.28278,0.0660,0.970343,0.00088,343.386,0.26,353.881,0.24,Raw data stored in - C:\Nu Noble\Results\Data...
10,TOM SM ST3,2020-06-24 12:08:00,0.113456,0.000036,0.000180,2.900000e-07,0.000300,4.200000e-07,0.000225,0.000017,...,6.100000e-08,1.21714,0.0230,0.971918,0.00180,378.730,0.55,389.672,0.50,Raw data stored in - C:\Nu Noble\Results\Data...
11,TOM SM ST4,2020-06-24 12:29:00,0.140526,0.000047,0.000288,4.000000e-07,0.000351,4.000000e-07,0.000363,0.000017,...,6.500000e-08,1.21116,0.0120,0.982168,0.00170,400.302,0.47,407.569,0.53,Raw data stored in - C:\Nu Noble\Results\Data...
12,TOM SM ST5,2020-06-24 12:57:00,0.341902,0.000110,0.000471,4.300000e-07,0.000922,7.800000e-07,0.000567,0.000017,...,5.600000e-08,1.18115,0.0089,0.979210,0.00110,370.815,0.33,378.688,0.31,Raw data stored in - C:\Nu Noble\Results\Data...
13,BAL-T12 SM ST5,2020-06-23 13:38:00,0.440568,0.000120,0.005370,4.100000e-06,0.000776,7.700000e-07,0.006207,0.000016,...,NaN,NaN,NaN,1.006620,0.00130,567.880,0.58,564.147,0.52,Raw data stored in - C:\Nu Noble\Results\Data...
14,BAL-T12 LG ST2,2020-06-23 15:31:00,0.426141,0.000120,0.003709,2.600000e-06,0.000883,7.200000e-07,0.004290,0.000017,...,NaN,NaN,NaN,0.997925,0.00120,482.535,0.42,483.538,0.46,Raw data stored in - C:\Nu Noble\Results\Data...
15,BAL-T12 LG ST3,2020-06-23 15:57:00,0.224427,0.000066,0.003784,2.800000e-06,0.000268,4.000000e-07,0.004378,0.000017,...,NaN,NaN,NaN,1.003020,0.00220,838.663,1.30,836.139,1.30,Raw data stored in - C:\Nu Noble\Results\Data...
16,BAL-T12 LG ST6,2020-06-23 17:08:00,0.421204,0.000130,0.004853,3.600000e-06,0.000743,7.200000e-07,0.005579,0.000016,...,NaN,NaN,NaN,1.008230,0.00130,567.014,0.58,562.386,0.54,Raw data stored in - C:\Nu Noble\Results\Data...
17,BAL-T12 ST7,2020-06-23 17:26:00,0.585912,0.000160,0.011360,1.100000e-05,0.000572,6.300000e-07,0.012936,0.000016,...,NaN,NaN,NaN,1.015770,0.00160,1024.300,1.20,1008.400,1.20,Raw data stored in - C:\Nu Noble\Results\Data...
18,Sample Name,2020-06-23 17:54:00,0.605563,0.000170,0.012759,1.100000e-05,0.000492,7.100000e-07,0.014504,0.000017,...,NaN,NaN,NaN,1.021820,0.00180,1230.700,1.80,1204.420,1.40,Raw data stored in - C:\Nu Noble\Results\Data...

## Operazioni derivate dal file di calibrazione

Prima di tutto si calcolano i gain dei colettori (aggiungere equazione?)

In [68]:
# calcolo gain F/IC0
value_36F = float(calibration_data['36F'].values)
value_36IC0 = float(calibration_data['36IC0'].values)
gain_F_IC0 = float(value_36F / value_36IC0)
print ('gain F/IC0: ', gain_F_IC0)

gain F/IC0:  1.1706467678512864

In [69]:
# calcolo gain F/IC1 
value_36F = float(calibration_data['36F'].values)
value_36IC1 = float(calibration_data['36IC1'].values)
gain_F_IC1 = float(value_36F / value_36IC1)
print ('gain F/IC1: ', gain_F_IC1)

gain F/IC1:  1.1343380401664318

In [70]:
# calcolo 36IC0 correzione gain
corr_gain_36IC0 = value_36IC0 * gain_F_IC0
print ('corr_gain_36IC0: ', corr_gain_36IC0)

corr_gain_36IC0:  346234.0

In [71]:
# calcolo 40/36 correzione
value_40F = float(calibration_data['40F'].values)
B = 62415000 #aggiungere descrizione della constante
corr_40_36 = (value_40F * B) / corr_gain_36IC0
print ('corr_40_36: ', corr_40_36)

corr_40_36:  298.17090926945366

Definisco tutti i parametri delle tabelle (A) e (B) del file excel (non sappiamo ancora da dove vengono presi tutti)

In [52]:
background_spectrometer_indexes = ['Update date', 'Background 40Ar', 'Background 39Ar', 'Background 38Ar', 'Background 37Ar', 'Background 36Ar']
# da modificare a mano 
update_data = pd.Timestamp(year=2021, month=1, day=23)

background_40Ar = 0.002
background_40Ar_errors = 0.1

background_39Ar = 0.003
background_39Ar_errors = 0.1

background_38Ar = 0.001
background_38Ar_errors = 0.1

background_37Ar = 0.004
background_37Ar_errors = 0.2

background_36Ar = 0.0005
background_36Ar_errors = 0.1

background_spectrometer_array = [update_data, background_40Ar, background_39Ar, background_38Ar, background_37Ar, background_36Ar]
background_spectrometer_array_errors = [np.nan, background_40Ar_errors, background_39Ar_errors, background_38Ar_errors, background_37Ar_errors, background_36Ar_errors]

background_spectrometer_df = pd.concat([pd.Series(background_spectrometer_array), pd.Series(background_spectrometer_array_errors)], axis = 1)
background_spectrometer_df.index = background_spectrometer_indexes #assegno i nomi delle righe 
background_spectrometer_df.columns = ['value', 'relative error']#assegno i nomi delle colonne

display(background_spectrometer_df)

                               value  relative error
Update date      2021-01-23 00:00:00             NaN
Background 40Ar                0.002             0.1
Background 39Ar                0.003             0.1
Background 38Ar                0.001             0.1
Background 37Ar                0.004             0.2
Background 36Ar               0.0005             0.1

In [107]:
irradiantions_indexes_constants = ['Atmospheric Ratio', '(36Ar/37Ar) Ca', '(38Ar/37Ar) Ca', '(39Ar/37Ar) Ca', \
                                   'Lambda Ar37 [1/d]', 'Lambda Ar40 [1/Ma]', 'Interference 40K', 'Coefficient 39Ar for J', \
                                   'Coefficient Ca/K', 'Coefficient Cl/K']
atmospheric_ratio = 
Ca_36Ar_37Ar = 
Ca_38Ar_37Ar =

irradiantions_values_constants = [298.56, 0.000255, 0.00027, 0.00067, 0.019748, 0.0005543, 0.033, 143, 1.94, 0.178]
irradiantions_values_constants_errors = [np.nan, 0.015, 0.015, 0.015, np.nan, np.nan, 0.01, np.nan, np.nan, np.nan]



irradiantions_indexes = ['Sample weight [g]', 'J factor', 'Sensitivity (mL/mV)', 'Gain F/IC0', 'Gain rel uncertainty', \
                         'Measured 40Ar/36Ar pipettes', 'Gain corrected 40Ar/36Ar pipettes', 'Pipette rel uncertainty', \
                        'Total fractionation uncertainty']
                                               
sample_weight = 0.00034
J_factor = 0.0011422
J_factor_errors = 0.0005
sensitivity = 0.0000000000337 

# gain_F_IC0 già calcolato precedentemente 

gain_rel_uncertainty_errors = calibration_data.loc['err 40F'].values / calibration_data.loc['err 36F'].values
gain_rel_uncertainty = gain_rel_uncertainty_errors.values / gain_F_IC0
measured_40Ar_36Ar_pipettes = calibration_data.loc['40F'].values / calibration_data.loc['36IC1'].values
gain_corrected_40Ar_36Ar_pipettes = measured_40Ar_36Ar_pipettes / gain_F_IC0
gain_corrected_40Ar_36Ar_pipettes_errors = gain_corrected_40Ar_36Ar_pipettes / irradiations_df.loc['Atmospheric Ratio']

# mandare email professore per chiedere come calcolare questo dato 
Pipette rel uncertainty = 
Total fractionation uncertainty = 

irradiantions_values = [sample_weight, J_factor, sensitivity, gain_F_IC0, gain_rel_uncertainty, measured_40Ar_36Ar_pipettes, \
                        gain_corrected_40Ar_36Ar_pipettes] 

irradiantions_values_errors = [np.nan, J_factor_errors, np.nan, gain_rel_uncertainty_errors, np.nan, \
                               gain_corrected_40Ar_36Ar_pipettes_errors, np.nan, np.nan, np.nan]  



irradiantions_df = pd.concat([pd.Series(irradiantions_values), pd.Series(irradiantions_values_errors)], axis = 1)
irradiantions_df.index = irradiantions_indexes #assegno i nomi delle righe
irradiantions_df.columns = ['value', 'relative error'] #assegno i nomi delle colonne

display(irradiantions_df)

                                          value  relative error
Sample weight [g]                  3.400000e-04             NaN
J factor                           1.142200e-03        0.000500
Atmospheric Ratio                  2.985600e+02             NaN
Gain F/IC0                         1.158935e+00             NaN
Gain rel uncertainty               4.111823e-03        0.004765
Measured 40Ar/36Ar pipettes        3.353102e+02             NaN
Gain corrected 40Ar/36Ar pipettes  2.893262e+02        0.969070
Pipette rel uncertainty            4.053522e-03             NaN
Total fractionation uncertainty    4.053522e-03             NaN
Sensitivity (mL/mV)                3.370000e-11             NaN
(36Ar/37Ar) Ca                     2.550000e-04        0.015000
(38Ar/37Ar) Ca                     2.700000e-04        0.015000
(39Ar/37Ar) Ca                     6.700000e-04        0.015000
Lambda Ar37 [1/d]                  1.974800e-02             NaN
Lambda Ar40 [1/Ma]                 5.543000e-04             NaN
Interference 40K                   3.300000e-02        0.010000
Coefficient 39Ar for J             1.430000e+02             NaN
Coefficient Ca/K                   1.940000e+00             NaN
Coefficient Cl/K                   1.780000e-01             NaN

###### Svolgimento operazioni presenti nel fogli excel CalcolAr

Le operazione necessarie verranno aggiunte in un unico dataframe di risultati simile a quello del file excel

In [108]:
input_data_df = pd.DataFrame()

input_data_df.loc[:, 'Time'] = pd.Series(1 for k in range(0, len(df_data.index)))
input_data_df.loc[:, 'Delay'] = pd.Series(delay for k in range(0, len(df_data.index)))


input_data_df.loc[:, '40Ar F'] = df_data.loc[:, '40Ar F'].values * 1000
input_data_df.loc[:, 'err40Ar F'] = df_data.loc[:, 'err40Ar F'].values * 1000

input_data_df.loc[:, '39Ar F'] = df_data.loc[:, '39Ar F'].values * 1000
input_data_df.loc[:, 'err39Ar F'] = df_data.loc[:, 'err39Ar F'].values * 1000

input_data_df.loc[:, '38Ar F'] = df_data.loc[:, '40Ar F'].values * 1000
input_data_df.loc[:, 'err38Ar F'] = df_data.loc[:, 'err38Ar F'].values * 1000

input_data_df.loc[:, '37Ar F'] = df_data.loc[:, '37Ar IC0'].values * df_data.loc[:, 'gainF/IC0'].values * 1000
input_data_df.loc[:, 'err37Ar F'] = df_data.loc[:, 'err37Ar IC0'].values * df_data.loc[:, 'gainF/IC0'].values * 1000

input_data_df.loc[:, '36Ar F'] = df_data.loc[:, '36Ar IC0'].values * df_data.loc[:, 'gainF/IC0'].values * 1000
input_data_df.loc[:, 'err36Ar F'] = df_data.loc[:, 'err36Ar IC0'].values * df_data.loc[:, 'gainF/IC0'].values * 1000

display(input_data_df)

,Time,Delay,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,36Ar F,err36Ar F
0,1,246,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,0.920375,0.000945
1,1,246,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,1.574512,0.001168
2,1,246,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,0.326051,0.000455
3,1,246,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,0.430510,0.000486
4,1,246,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,3.158987,0.001746
5,1,246,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,0.237441,0.000404
6,1,246,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,0.373737,0.000450
7,1,246,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,0.657296,0.000723
8,1,246,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,0.571383,0.000682
9,1,246,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,2.343075,0.001411
10,1,246,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,0.354380,0.000438
11,1,246,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,0.417596,0.000521
12,1,246,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,1.066412,0.000815
13,1,246,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,NaN,NaN
14,1,246,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,NaN,NaN
15,1,246,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,NaN,NaN
16,1,246,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,NaN,NaN
17,1,246,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,NaN,NaN
18,1,246,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,NaN,NaN

In [109]:
results_data = input_data_df

results_data.loc[:,'40Ar BC'] = results_data.loc[:, '40Ar F'].values - (results_data.loc[:, '39Ar F'].values * \
                                       irradiantions_df.loc['Interference 40K', 'value']) - background_spectrometer_df.loc['Background 40Ar', 'value']

results_data.loc[:,'1sigma_abs40'] = (pow(results_data.loc[:, 'err40Ar F'].values, 2) + pow(background_spectrometer_df.loc['Background 40Ar', 'value'] * \
                                                                                            background_spectrometer_df.loc['Background 40Ar', 'relative error'], 2))**(1/2)

results_data.loc[:,'1sigma_rel40'] = results_data.loc[:,'1sigma_abs40'].values / results_data.loc[:,'40Ar BC'].values

results_data.loc[:,'39Ar BC'] = results_data.loc[:, '39Ar F'].values - background_spectrometer_df.loc['Background 39Ar', 'value']

results_data.loc[:,'1sigma_abs39'] = (pow(results_data.loc[:, 'err39Ar F'].values, 2) + pow(background_spectrometer_df.loc['Background 39Ar', 'value'] * \
                                                                                            background_spectrometer_df.loc['Background 39Ar', 'relative error'], 2))**(1/2)

results_data.loc[:,'1sigma_rel39'] = results_data.loc[:,'1sigma_abs39'].values / results_data.loc[:,'39Ar BC'].values

results_data.loc[:,'38Ar BC'] = results_data.loc[:, '38Ar F'].values - background_spectrometer_df.loc['Background 38Ar', 'value']

results_data.loc[:,'1sigma_abs38'] = (pow(results_data.loc[:, 'err38Ar F'].values, 2) + pow(background_spectrometer_df.loc['Background 38Ar', 'value'] * \
                                                                                            background_spectrometer_df.loc['Background 38Ar', 'relative error'], 2))**(1/2)

results_data.loc[:,'1sigma_rel38'] = results_data.loc[:,'1sigma_abs38'].values / results_data.loc[:,'38Ar BC'].values

results_data.loc[:,'37Ar BC'] = results_data.loc[:, '37Ar F'].values - background_spectrometer_df.loc['Background 37Ar', 'value']

results_data.loc[:,'1sigma_abs37'] = (pow(results_data.loc[:, 'err37Ar F'].values, 2) + pow(background_spectrometer_df.loc['Background 37Ar', 'value'] * \
                                                                                            background_spectrometer_df.loc['Background 37Ar', 'relative error'], 2))**(1/2)

results_data.loc[:,'1sigma_rel37'] = results_data.loc[:,'1sigma_abs37'].values / results_data.loc[:,'37Ar BC'].values

results_data.loc[:,'36Ar BC'] = results_data.loc[:, '36Ar F'].values - background_spectrometer_df.loc['Background 36Ar', 'value']

results_data.loc[:,'1sigma_abs36'] = (pow(results_data.loc[:, 'err36Ar F'].values, 2) + pow(background_spectrometer_df.loc['Background 36Ar', 'value'] * \
                                                                                            background_spectrometer_df.loc['Background 36Ar', 'relative error'], 2))**(1/2)

results_data.loc[:,'1sigma_rel36'] = results_data.loc[:,'1sigma_abs36'].values / results_data.loc[:,'36Ar BC'].values


display(results_data)

,Time,Delay,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,...,1sigma_rel39,38Ar BC,1sigma_abs38,1sigma_rel38,37Ar BC,1sigma_abs37,1sigma_rel37,36Ar BC,1sigma_abs36,1sigma_rel36
0,1,246,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,...,0.009906,277.141,0.017,0.000061,0.004214,0.000803,0.190679,0.919875,0.000946,0.001028
1,1,246,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,...,0.000941,516.113,0.014,0.000027,0.005345,0.000803,0.150292,1.574012,0.001169,0.000743
2,1,246,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,...,0.001141,134.761,0.014,0.000104,0.004279,0.000804,0.187977,0.325551,0.000458,0.001408
3,1,246,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,...,0.000926,177.960,0.014,0.000079,0.005513,0.000802,0.145542,0.430010,0.000489,0.001136
4,1,246,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,...,0.001858,963.264,0.017,0.000018,0.008839,0.000805,0.091122,3.158487,0.001747,0.000553
5,1,246,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,...,0.000823,133.249,0.015,0.000113,0.004911,0.000803,0.163504,0.236941,0.000407,0.001717
6,1,246,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,...,0.001056,164.827,0.015,0.000091,0.006451,0.000804,0.124667,0.373237,0.000453,0.001213
7,1,246,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,...,0.001087,224.256,0.015,0.000067,0.004130,0.000803,0.194459,0.656796,0.000725,0.001104
8,1,246,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,...,0.093741,143.380,0.018,0.000126,0.004403,0.000805,0.182788,0.570883,0.000684,0.001197
9,1,246,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,...,0.053371,646.385,0.016,0.000025,0.004815,0.000805,0.167251,2.342575,0.001412,0.000603
10,1,246,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,...,0.019581,113.455,0.017,0.000150,0.003137,0.000803,0.255854,0.353880,0.000441,0.001246
11,1,246,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,...,0.010019,140.525,0.017,0.000121,0.003464,0.000803,0.231760,0.417096,0.000523,0.001254
12,1,246,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,...,0.007555,341.901,0.017,0.000050,0.003430,0.000804,0.234364,1.065912,0.000817,0.000766
13,1,246,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,...,0.000481,440.567,0.016,0.000036,NaN,NaN,NaN,NaN,NaN,NaN
14,1,246,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,...,0.000580,426.140,0.017,0.000040,NaN,NaN,NaN,NaN,NaN,NaN
15,1,246,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,...,0.000519,224.426,0.017,0.000076,NaN,NaN,NaN,NaN,NaN,NaN
16,1,246,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,...,0.000488,421.203,0.016,0.000038,NaN,NaN,NaN,NaN,NaN,NaN
17,1,246,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,...,0.000354,585.911,0.016,0.000027,NaN,NaN,NaN,NaN,NaN,NaN
18,1,246,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,...,0.000329,605.562,0.017,0.000028,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
#results_data.loc[:,'Decay Factor'] = (irradiantions_df.loc['Lambda Ar37 [1/d]', 'value'] * \
#                                      results_data.loc[:, 'Time'].values * \
#                                        math.exp(irradiantions_df.loc['Lambda Ar37 [1/d]', 'value'] * \
 #                                       results_data.loc[:, 'Delay'].values))/(1-math.exp((-1) * \
 #                                       irradiantions_df.loc['Lambda Ar37 [1/d]', 'value'] * results_data.loc[:, 'Time'].values))

results_data.loc[:,'Decay Factor'] = (irradiantions_df.loc['Lambda Ar37 [1/d]', 'value'] * \
                                      1 * \
                                        math.exp(irradiantions_df.loc['Lambda Ar37 [1/d]', 'value'] * \
                                        246))/(1-math.exp((-1) * \
                                        irradiantions_df.loc['Lambda Ar37 [1/d]', 'value'] * 1))



display(results_data)

,Time,Delay,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,...,37Ar BC,1sigma_abs37,1sigma_rel37,36Ar BC,1sigma_abs36,1sigma_rel36,Mult 4amu,Mult 2amu,Mult 1amu,Decay Factor
0,1,246,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,...,0.004214,0.000803,0.190679,0.919875,0.000946,0.001028,0.96907,0.984535,0.992267,130.043076
1,1,246,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,...,0.005345,0.000803,0.150292,1.574012,0.001169,0.000743,0.96907,0.984535,0.992267,130.043076
2,1,246,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,...,0.004279,0.000804,0.187977,0.325551,0.000458,0.001408,0.96907,0.984535,0.992267,130.043076
3,1,246,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,...,0.005513,0.000802,0.145542,0.430010,0.000489,0.001136,0.96907,0.984535,0.992267,130.043076
4,1,246,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,...,0.008839,0.000805,0.091122,3.158487,0.001747,0.000553,0.96907,0.984535,0.992267,130.043076
5,1,246,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,...,0.004911,0.000803,0.163504,0.236941,0.000407,0.001717,0.96907,0.984535,0.992267,130.043076
6,1,246,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,...,0.006451,0.000804,0.124667,0.373237,0.000453,0.001213,0.96907,0.984535,0.992267,130.043076
7,1,246,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,...,0.004130,0.000803,0.194459,0.656796,0.000725,0.001104,0.96907,0.984535,0.992267,130.043076
8,1,246,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,...,0.004403,0.000805,0.182788,0.570883,0.000684,0.001197,0.96907,0.984535,0.992267,130.043076
9,1,246,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,...,0.004815,0.000805,0.167251,2.342575,0.001412,0.000603,0.96907,0.984535,0.992267,130.043076
10,1,246,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,...,0.003137,0.000803,0.255854,0.353880,0.000441,0.001246,0.96907,0.984535,0.992267,130.043076
11,1,246,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,...,0.003464,0.000803,0.231760,0.417096,0.000523,0.001254,0.96907,0.984535,0.992267,130.043076
12,1,246,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,...,0.003430,0.000804,0.234364,1.065912,0.000817,0.000766,0.96907,0.984535,0.992267,130.043076
13,1,246,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267,130.043076
14,1,246,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267,130.043076
15,1,246,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267,130.043076
16,1,246,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267,130.043076
17,1,246,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267,130.043076
18,1,246,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267,130.043076

In [111]:
results_data.loc[:,'Mult 4amu'] = irradiantions_df.loc['Gain corrected 40Ar/36Ar pipettes', 'relative error']
results_data.loc[:,'Mult 2amu'] = (results_data.loc[:,'Mult 4amu'].values + 1) / 2
results_data.loc[:,'Mult 1amu'] = (results_data.loc[:,'Mult 4amu'].values + 3) / 4


display(results_data)

,Time,Delay,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,...,1sigma_rel38,37Ar BC,1sigma_abs37,1sigma_rel37,36Ar BC,1sigma_abs36,1sigma_rel36,Mult 4amu,Mult 2amu,Mult 1amu
0,1,246,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,...,0.000061,0.004214,0.000803,0.190679,0.919875,0.000946,0.001028,0.96907,0.984535,0.992267
1,1,246,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,...,0.000027,0.005345,0.000803,0.150292,1.574012,0.001169,0.000743,0.96907,0.984535,0.992267
2,1,246,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,...,0.000104,0.004279,0.000804,0.187977,0.325551,0.000458,0.001408,0.96907,0.984535,0.992267
3,1,246,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,...,0.000079,0.005513,0.000802,0.145542,0.430010,0.000489,0.001136,0.96907,0.984535,0.992267
4,1,246,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,...,0.000018,0.008839,0.000805,0.091122,3.158487,0.001747,0.000553,0.96907,0.984535,0.992267
5,1,246,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,...,0.000113,0.004911,0.000803,0.163504,0.236941,0.000407,0.001717,0.96907,0.984535,0.992267
6,1,246,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,...,0.000091,0.006451,0.000804,0.124667,0.373237,0.000453,0.001213,0.96907,0.984535,0.992267
7,1,246,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,...,0.000067,0.004130,0.000803,0.194459,0.656796,0.000725,0.001104,0.96907,0.984535,0.992267
8,1,246,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,...,0.000126,0.004403,0.000805,0.182788,0.570883,0.000684,0.001197,0.96907,0.984535,0.992267
9,1,246,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,...,0.000025,0.004815,0.000805,0.167251,2.342575,0.001412,0.000603,0.96907,0.984535,0.992267
10,1,246,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,...,0.000150,0.003137,0.000803,0.255854,0.353880,0.000441,0.001246,0.96907,0.984535,0.992267
11,1,246,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,...,0.000121,0.003464,0.000803,0.231760,0.417096,0.000523,0.001254,0.96907,0.984535,0.992267
12,1,246,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,...,0.000050,0.003430,0.000804,0.234364,1.065912,0.000817,0.000766,0.96907,0.984535,0.992267
13,1,246,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,...,0.000036,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267
14,1,246,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,...,0.000040,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267
15,1,246,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,...,0.000076,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267
16,1,246,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,...,0.000038,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267
17,1,246,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,...,0.000027,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267
18,1,246,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,...,0.000028,NaN,NaN,NaN,NaN,NaN,NaN,0.96907,0.984535,0.992267

In [56]:
results_data.loc[:,'Ar36tot'] = results_data.loc[:,'36Ar BC'].values * results_data.loc[:,'Mult 4amu'].values
results_data.loc[:,'1sigRel36tot'] = (pow(results_data.loc[:,'1sigma_rel36'].values, 2) + pow(irradiantions_df.loc['Total fractionation uncertainty', 'value'], 2))**(1/2)

results_data.loc[:,'Ar38tot'] = results_data.loc[:,'38Ar BC'].values * results_data.loc[:,'Mult 2amu'].values
results_data.loc[:,'1sigRel38tot'] = (pow(results_data.loc[:,'1sigma_rel38'].values, 2) + 0.25 * pow(irradiantions_df.loc['Total fractionation uncertainty', 'value'], 2))**(1/2)

results_data.loc[:,'Ar39tot'] = results_data.loc[:,'39Ar BC'].values * results_data.loc[:,'Mult 1amu'].values
results_data.loc[:,'1sigRel39tot'] = (pow(results_data.loc[:,'1sigma_rel39'].values, 2) + 0.0625 * pow(irradiantions_df.loc['Total fractionation uncertainty', 'value'], 2))**(1/2)
                                                                        
display(results_data)

,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,36Ar F,err36Ar F,...,Decay Factor,Mult 4amu,Mult 2amu,Mult 1amu,Ar36tot,1sigRel36tot,Ar38tot,1sigRel38tot,Ar39tot,1sigRel39tot
0,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,0.920375,0.000945,...,130.043076,0.96907,0.984535,0.992267,0.891423,0.004182,272.855014,0.002028,1.603018,0.009957
1,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,1.574512,0.001168,...,130.043076,0.96907,0.984535,0.992267,1.525327,0.004121,508.131312,0.002027,14.770398,0.001383
2,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,0.326051,0.000455,...,130.043076,0.96907,0.984535,0.992267,0.315481,0.004291,132.676921,0.002029,12.177404,0.001526
3,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,0.430510,0.000486,...,130.043076,0.96907,0.984535,0.992267,0.416710,0.004210,175.207849,0.002028,16.080786,0.001373
4,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,3.158987,0.001746,...,130.043076,0.96907,0.984535,0.992267,3.060795,0.004091,948.367122,0.002027,9.081242,0.002116
5,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,0.237441,0.000404,...,130.043076,0.96907,0.984535,0.992267,0.229612,0.004402,131.188304,0.002030,19.286604,0.001306
6,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,0.373737,0.000450,...,130.043076,0.96907,0.984535,0.992267,0.361692,0.004231,162.277950,0.002029,16.913795,0.001464
7,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,0.657296,0.000723,...,130.043076,0.96907,0.984535,0.992267,0.636482,0.004201,220.787881,0.002028,12.779810,0.001486
8,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,0.571383,0.000682,...,130.043076,0.96907,0.984535,0.992267,0.553226,0.004227,141.162628,0.002031,0.190560,0.093747
9,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,2.343075,0.001411,...,130.043076,0.96907,0.984535,0.992267,2.270119,0.004098,636.388656,0.002027,0.297523,0.053380
10,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,0.354380,0.000438,...,130.043076,0.96907,0.984535,0.992267,0.342935,0.004241,111.700418,0.002032,0.912262,0.019608
11,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,0.417596,0.000521,...,130.043076,0.96907,0.984535,0.992267,0.404195,0.004243,138.351781,0.002030,1.683848,0.010071
12,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,1.066412,0.000815,...,130.043076,0.96907,0.984535,0.992267,1.032943,0.004125,336.613501,0.002027,2.233227,0.007622
13,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,NaN,NaN,...,130.043076,0.96907,0.984535,0.992267,NaN,NaN,433.753631,0.002027,55.648147,0.001122
14,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,NaN,NaN,...,130.043076,0.96907,0.984535,0.992267,NaN,NaN,419.549745,0.002027,37.643950,0.001168
15,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,NaN,NaN,...,130.043076,0.96907,0.984535,0.992267,NaN,NaN,220.955252,0.002028,40.155677,0.001139
16,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,NaN,NaN,...,130.043076,0.96907,0.984535,0.992267,NaN,NaN,414.689096,0.002027,50.842794,0.001125
17,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,NaN,NaN,...,130.043076,0.96907,0.984535,0.992267,NaN,NaN,576.849886,0.002027,120.381893,0.001074
18,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,NaN,NaN,...,130.043076,0.96907,0.984535,0.992267,NaN,NaN,596.196984,0.002027,135.713418,0.001065

In [57]:
# ripreso le operazioni da qui in poi 

results_data.loc[:,'Ar37day0'] = results_data.loc[:, 'Decay Factor'].values * results_data.loc[:,'37Ar BC'].values * (results_data.loc[:,'Mult 4amu'].values * results_data.loc[:,'Mult 2amu'])
results_data.loc[:,'1sigRel37corr'] = (((pow(results_data.loc[:,'1sigma_rel37'].values, 2) + pow(irradiantions_df.loc['Total fractionation uncertainty', 'value'], 2)) * 9) / 16)**(1/2)
                                        
display(results_data)

,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,36Ar F,err36Ar F,...,Mult 2amu,Mult 1amu,Ar36tot,1sigRel36tot,Ar38tot,1sigRel38tot,Ar39tot,1sigRel39tot,Ar37day0,1sigRel37corr
0,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,0.920375,0.000945,...,0.984535,0.992267,0.891423,0.004182,272.855014,0.002028,1.603018,0.009957,0.522779,0.143041
1,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,1.574512,0.001168,...,0.984535,0.992267,1.525327,0.004121,508.131312,0.002027,14.770398,0.001383,0.663130,0.112760
2,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,0.326051,0.000455,...,0.984535,0.992267,0.315481,0.004291,132.676921,0.002029,12.177404,0.001526,0.530860,0.141015
3,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,0.430510,0.000486,...,0.984535,0.992267,0.416710,0.004210,175.207849,0.002028,16.080786,0.001373,0.684061,0.109199
4,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,3.158987,0.001746,...,0.984535,0.992267,3.060795,0.004091,948.367122,0.002027,9.081242,0.002116,1.096634,0.068409
5,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,0.237441,0.000404,...,0.984535,0.992267,0.229612,0.004402,131.188304,0.002030,19.286604,0.001306,0.609332,0.122666
6,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,0.373737,0.000450,...,0.984535,0.992267,0.361692,0.004231,162.277950,0.002029,16.913795,0.001464,0.800347,0.093550
7,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,0.657296,0.000723,...,0.984535,0.992267,0.636482,0.004201,220.787881,0.002028,12.779810,0.001486,0.512446,0.145876
8,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,0.571383,0.000682,...,0.984535,0.992267,0.553226,0.004227,141.162628,0.002031,0.190560,0.093747,0.546331,0.137125
9,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,2.343075,0.001411,...,0.984535,0.992267,2.270119,0.004098,636.388656,0.002027,0.297523,0.053380,0.597407,0.125475
10,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,0.354380,0.000438,...,0.984535,0.992267,0.342935,0.004241,111.700418,0.002032,0.912262,0.019608,0.389205,0.191915
11,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,0.417596,0.000521,...,0.984535,0.992267,0.404195,0.004243,138.351781,0.002030,1.683848,0.010071,0.429759,0.173847
12,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,1.066412,0.000815,...,0.984535,0.992267,1.032943,0.004125,336.613501,0.002027,2.233227,0.007622,0.425586,0.175799
13,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,NaN,NaN,...,0.984535,0.992267,NaN,NaN,433.753631,0.002027,55.648147,0.001122,NaN,NaN
14,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,NaN,NaN,...,0.984535,0.992267,NaN,NaN,419.549745,0.002027,37.643950,0.001168,NaN,NaN
15,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,NaN,NaN,...,0.984535,0.992267,NaN,NaN,220.955252,0.002028,40.155677,0.001139,NaN,NaN
16,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,NaN,NaN,...,0.984535,0.992267,NaN,NaN,414.689096,0.002027,50.842794,0.001125,NaN,NaN
17,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,NaN,NaN,...,0.984535,0.992267,NaN,NaN,576.849886,0.002027,120.381893,0.001074,NaN,NaN
18,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,NaN,NaN,...,0.984535,0.992267,NaN,NaN,596.196984,0.002027,135.713418,0.001065,NaN,NaN

In [58]:
results_data.loc[:,'Ar39Ca'] = results_data.loc[:,'Ar37day0'].values * (irradiantions_df.loc['(39Ar/37Ar) Ca', 'value'])                                      
results_data.loc[:,'1sigRel39Ca'] = (pow(results_data.loc[:,'1sigRel37corr'].values, 2) + 0.000225)**(1/2)
results_data.loc[:,'1sigAbs39Ca'] = results_data.loc[:,'1sigRel39Ca'].values * results_data.loc[:,'Ar39Ca'].values  

results_data.loc[:,'Ar39K'] = results_data.loc[:,'Ar39tot'].values - results_data.loc[:,'Ar39Ca'].values
results_data.loc[:,'1sigAbs39K'] = (pow(results_data.loc[:,'1sigAbs39Ca'].values,2) + \
                                    pow(results_data.loc[:,'1sigRel39tot'].values * results_data.loc[:,'Ar39tot'].values, 2))**(1/2)

results_data.loc[:,'Ar36Ca'] = results_data.loc[:,'Ar37day0'].values * irradiantions_df.loc['(36Ar/37Ar) Ca', 'value']  
results_data.loc[:,'1sigRel36Ca'] = (pow(results_data.loc[:,'1sigRel37corr'].values, 2) + 0.000225)**(1/2)                                                                     
results_data.loc[:,'1sigAbs36Ca'] = results_data.loc[:,'1sigRel36Ca'].values * results_data.loc[:,'Ar36Ca'].values
                                                                        
results_data.loc[:,'Ar36Atm'] = results_data.loc[:,'Ar36tot'].values - results_data.loc[:,'Ar36Ca'].values
results_data.loc[:,'1sigAbs36Atm'] = (pow(results_data.loc[:,'1sigAbs36Ca'].values,2) + pow(results_data.loc[:,'1sigRel36tot'].values * results_data.loc[:,'Ar36tot'].values, 2))**(1/2)  
results_data.loc[:,'1sigRel36Atm'] = results_data.loc[:,'1sigAbs36Atm'].values / results_data.loc[:,'Ar36Atm'].values
                                        
results_data.loc[:,'Ar40Atm'] = results_data.loc[:,'Ar36Atm'].values * irradiantions_df.loc['Atmospheric Ratio', 'value'] 
results_data.loc[:,'1sigAbs40Atm'] = results_data.loc[:,'Ar40Atm'].values * results_data.loc[:,'1sigRel36Atm'].values

results_data.loc[:, 'Ar40*'] = results_data.loc[:,'40Ar BC'].values - results_data.loc[:,'Ar40Atm'].values
results_data.loc[:,'1sigAbs40*'] = (pow(results_data.loc[:,'1sigma_abs40'].values, 2) + pow(results_data.loc[:,'1sigAbs40Atm'].values, 2))**(1/2)

                                     
results_data.loc[:,'rendimento rad'] = results_data.loc[:, 'Ar40*'].values / results_data.loc[:,'40Ar BC'].values
results_data.loc[:,'error magnif'] = 1 - (results_data.loc[:,'rendimento rad'].values - 1)
results_data.loc[:,'error36*magnif'] = results_data.loc[:,'1sigRel36Atm'].values * results_data.loc[:,'error magnif'].values

                                     
results_data.loc[:,'1sigRel40*'] = results_data.loc[:,'1sigAbs40*'].values / results_data.loc[:, 'Ar40*'] 
results_data.loc[:,'Ar38Cl'] = (results_data.loc[:,'Ar38tot'].values - results_data.loc[:,'Ar39K'].values) / 90 - (results_data.loc[:,'Ar36Atm'].values * 0.18855) - (results_data.loc[:,'Ar37day0'].values * 0.00027)
results_data.loc[:,'1sigAbs38Cl'] = (pow(results_data.loc[:,'1sigRel38tot'].values, 2) + \
                                      pow((results_data.loc[:,'1sigAbs39K'].values / 85), 2) + \
                                       pow((results_data.loc[:,'1sigAbs36Atm'].values * 0.18855), 2) + \
                                        pow((results_data.loc[:,'1sigRel37corr'].values * results_data.loc[:,'Ar37day0'].values * 0.00027), 2))**(1/2)

results_data.loc[:,'1sigRel38Cl'] = results_data.loc[:,'1sigAbs38Cl'].values / results_data.loc[:,'Ar38Cl'].values


# colonna vuota (BK nel foglio excel)   


#colonne RESULTS

results_data.loc[:,'40Ar_total'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:,'40Ar BC'].values
results_data.loc[:,'err_40Ar'] = results_data.loc[:,'40Ar_total'].values * results_data.loc[:,'1sigma_rel40'].values

results_data.loc[:,'40Ar*'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:, 'Ar40*'].values
results_data.loc[:, 'err_40Ar*'] = results_data.loc[:,'1sigRel40*'].values * results_data.loc[:,'40Ar*'].values

results_data.loc[:,'39Ar'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:,'Ar39tot'].values
results_data.loc[:,'err_39Ar'] = results_data.loc[:,'39Ar'] * results_data.loc[:,'1sigRel39tot'].values

# inserire variabile cella BP3 = sommatoria colonne 39Ar (BP)
total_mL_K = results_data.loc[:,'39Ar'].sum()

results_data.loc[:,'% 39Ar'] = 100 * (results_data.loc[:,'39Ar'].values / total_mL_K)                                                         

results_data.loc[:,'38Ar'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:,'Ar38tot'].values                                                                                           
results_data.loc[:,'err_38Ar'] = results_data.loc[:,'38Ar'].values * results_data.loc[:,'1sigRel38tot'].values

results_data.loc[:,'38Ar_Cl'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:,'Ar38Cl'].values
results_data.loc[:,'err_38Cl'] = results_data.loc[:,'1sigRel38Cl'].values * results_data.loc[:,'38Ar_Cl'].values
                                 
results_data.loc[:,'37Ar'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:,'Ar37day0'].values
results_data.loc[:,'err_37Ar'] = results_data.loc[:,'1sigRel37corr'].values *  results_data.loc[:,'37Ar'].values

results_data.loc[:,'36Ar'] = irradiantions_df.loc['Sensitivity (mL/mV)', 'value'] * results_data.loc[:,'Ar36tot'].values
results_data.loc[:,'err_36Ar'] = results_data.loc[:,'1sigRel36tot'].values * results_data.loc[:,'36Ar'].values

results_data.loc[:,'Age'] = np.log(1 + (results_data.loc[:, '40Ar*'].values * \
                                        irradiantions_df.loc['J factor', 'value'] / \
                                        results_data.loc[:,'Ar39K'].values) / \
                                   irradiantions_df.loc['Lambda Ar40 [1/Ma]', 'value'])


results_data.loc[:,'1sigma_err_Age'] = results_data.loc[:,'Age'].values * \
                                        (pow(irradiantions_df.loc['J factor', 'relative error'], 2) * \
                                         pow(results_data.loc[:,'1sigRel40*'].values, 2) * \
                                         pow(results_data.loc[:,'1sigAbs39K'].values / \
                                             results_data.loc[:,'Ar39K'].values, 2))**(1/2)

results_data.loc[:,'Age+2error'] = results_data.loc[:,'Age'].values + 2 * results_data.loc[:,'1sigma_err_Age'].values
results_data.loc[:,'Age-2error'] = results_data.loc[:,'Age'].values - 2 * results_data.loc[:,'1sigma_err_Age'].values    

results_data.loc[:,'Ca/K'] =  results_data.loc[:,'Ar37day0'].values * (1.94 / results_data.loc[:,'Ar39K'].values)   
results_data.loc[:,'err_Ca/K'] = results_data.loc[:,'Ca/K'].values * \
                                    (pow(results_data.loc[:,'1sigRel37corr'].values, 2) + \
                                     pow(results_data.loc[:,'1sigAbs39K'].values / results_data.loc[:,'Ar39K'].values, 2))**(1/2)

results_data.loc[:,'Cl/K'] = irradiantions_df.loc['Coefficient Cl/K', 'value'] * (results_data.loc[:,'38Ar_Cl'].values * results_data.loc[:,'39Ar'].values)
results_data.loc[:,'err_Cl/K'] = results_data.loc[:,'Cl/K'].values * \
                                    (pow(results_data.loc[:,'1sigRel38Cl'].values, 2) + \
                                     pow(results_data.loc[:,'1sigAbs39K'].values / \
                                         results_data.loc[:,'Ar39K'].values, 2))**(1/2)

results_data.loc[:,'39/40'] = results_data.loc[:,'Ar39K'].values / results_data.loc[:,'40Ar BC'].values
results_data.loc[:,'Sig_9'] = results_data.loc[:,'39/40'] * \
                                (pow(results_data.loc[:,'1sigma_rel40'].values, 2) + \
                                 pow(results_data.loc[:,'1sigAbs39K'].values / \
                                     results_data.loc[:,'Ar39K'].values, 2))**(1/2)

results_data.loc[:,'36/40'] = (results_data.loc[:,'Ar36tot'].values - (results_data.loc[:,'Ar37day0'].values * \
                                irradiantions_df.loc['(36Ar/37Ar) Ca', 'value'])) / results_data.loc[:,'40Ar BC'].values
results_data.loc[:,'Sig_6'] = results_data.loc[:,'36/40'].values * (pow(results_data.loc[:,'1sigma_rel40'].values, 2) + \
                                                                    pow(results_data.loc[:,'1sigRel36Atm'].values, 2))**(1/2)

display(results_data)

,40Ar F,err40Ar F,39Ar F,err39Ar F,38Ar F,err38Ar F,37Ar F,err37Ar F,36Ar F,err36Ar F,...,Age+2error,Age-2error,Ca/K,err_Ca/K,Cl/K,err_Cl/K,39/40,Sig_9,36/40,Sig_6
0,277.142,0.093,1.618510,0.016,277.142,0.017,0.008214,0.000074,0.920375,0.000945,...,4.758885e-10,4.758875e-10,0.632815,0.090738,9.221691e-22,9.210986e-24,0.005784,0.000058,0.003217,0.000013
1,516.114,0.160,14.888500,0.014,516.114,0.014,0.009345,0.000072,1.574512,0.001168,...,2.833642e-10,2.833642e-10,0.087101,0.009822,1.550878e-20,2.257341e-23,0.028645,0.000041,0.002958,0.000012
2,134.762,0.038,12.275300,0.014,134.762,0.014,0.008279,0.000083,0.326051,0.000455,...,2.292808e-10,2.292808e-10,0.084575,0.011927,3.149213e-21,6.981683e-24,0.090633,0.000141,0.002347,0.000010
3,177.961,0.059,16.209100,0.015,177.961,0.014,0.009513,0.000062,0.430510,0.000486,...,2.291529e-10,2.291529e-10,0.082528,0.009013,5.491735e-21,1.010792e-23,0.090632,0.000128,0.002348,0.000010
4,963.265,0.270,9.155010,0.017,963.265,0.017,0.012839,0.000093,3.158987,0.001746,...,3.763568e-10,3.763567e-10,0.234290,0.016035,1.809944e-20,3.873142e-23,0.009430,0.000020,0.003178,0.000013
5,133.250,0.043,19.439900,0.016,133.250,0.015,0.008911,0.000069,0.237441,0.000404,...,2.308014e-10,2.308014e-10,0.061293,0.007519,4.678330e-21,1.009166e-23,0.145439,0.000196,0.001730,0.000008
6,164.828,0.057,17.048600,0.018,164.828,0.015,0.010451,0.000082,0.373737,0.000450,...,2.313114e-10,2.313114e-10,0.091802,0.008589,5.288735e-21,1.048891e-23,0.102964,0.000155,0.002201,0.000009
7,224.257,0.075,12.882400,0.014,224.257,0.015,0.008130,0.000071,0.657296,0.000723,...,1.838896e-10,1.838896e-10,0.077792,0.011349,5.660606e-21,1.001336e-23,0.057095,0.000087,0.002843,0.000012
8,143.381,0.050,0.195045,0.018,143.381,0.018,0.008403,0.000088,0.571383,0.000682,...,-7.943801e-09,-7.943753e-09,5.572639,0.926224,5.631676e-23,5.290295e-24,0.001327,0.000125,0.003858,0.000016
9,646.386,0.210,0.302842,0.016,646.386,0.016,0.008815,0.000092,2.343075,0.001411,...,-7.326409e-09,-7.326340e-09,3.900638,0.531992,3.993353e-22,2.134613e-23,0.000460,0.000025,0.003512,0.000014
10,113.456,0.036,0.922371,0.018,113.456,0.017,0.007137,0.000065,0.354380,0.000438,...,8.426526e-10,8.426513e-10,0.827913,0.159716,2.150729e-22,4.235369e-24,0.008041,0.000158,0.003023,0.000013
11,140.526,0.047,1.699970,0.017,140.526,0.017,0.007464,0.000067,0.417596,0.000521,...,8.176979e-10,8.176975e-10,0.495219,0.086237,4.909272e-22,4.994511e-24,0.011985,0.000121,0.002877,0.000012
12,341.902,0.110,2.253630,0.017,341.902,0.017,0.007430,0.000079,1.066412,0.000815,...,1.040658e-09,1.040658e-09,0.369753,0.065063,1.589333e-21,1.215622e-23,0.006532,0.000050,0.003022,0.000013
13,440.568,0.120,56.084800,0.027,440.568,0.016,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,426.141,0.120,37.940300,0.022,426.141,0.017,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,224.427,0.066,40.471600,0.021,224.427,0.017,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,421.204,0.130,51.242000,0.025,421.204,0.016,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,585.912,0.160,121.323000,0.043,585.912,0.016,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,605.563,0.170,136.774000,0.045,605.563,0.017,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# for spectrum 
results_data.loc[:,'cum_%39'] = 
results_data.loc[:,'Age+'] = 
results_data.loc[:,'Age+'] =

SyntaxError: invalid syntax (<ipython-input-59-247d53860616>, line 2)