# PyCalcolAr: questo e il file finale con tutte le operazioni insieme

In [14]:

#imports
import pandas as pd
import numpy as np
import math 

from IPython.display import display

Inizio importanto il file Triplo 36 (che per ora terrò separato dagli altri dataframe di dati Run4 e Run22)

In [15]:
delay = 246

columns_names=['40F', 'err 40F', '38IC0', 'err 38IC0', '36IC1', 'err 36IC1', '36IC0', 'err 36IC0','36F', 'err 36F', 'gain IC0/IC1', 'err gain IC0/IC1', 'gain F/IC1', 'err gain F/IC1' , 'gain F/IC0', 'err gain F/IC0', '40F/36IC1', 'err 40F/36IC1 ', '40F/36F', 'err 40F/36F', '40F/36IC0', 'err 40F/36IC0' , '38IC0/36IC0', 'err 38IC0/36IC0', 'Run', 'Path']
file_path = "../test_data/Triplo36.txt"
airpipette_data = pd.read_csv(file_path, header = None, names = columns_names, sep = '\t|,', engine = 'python')  # abbiamo usato come separatore
                                                                                                    #entrambi i caratteri ',' (virgola) 
                                                                                                    #e '\t' (tab)

#si eliminano i charatteri "{}" dalle colonne relative all'errore
airpipette_data = airpipette_data.replace(["{", "}"], ["", ""], regex=True)

#tengo solo le colonne di interesse
airpipette_data = airpipette_data[['40F', 'err 40F', '38IC0', 'err 38IC0', '36IC1', 'err 36IC1', '36IC0', 'err 36IC0','36F', 'err 36F', 'Run', 'Path']]


print("Air pipette initial imported data:")
display(airpipette_data)

Air pipette initial imported data:

,40F,err 40F,38IC0,err 38IC0,36IC1,err 36IC1,36IC0,err 36IC0,36F,err 36F,Run,Path
0,0.73900,4.0e-03,49900.0,5.8e+01,72000.0,2.3e+02,259000.0,1.6e+02,144000.0,1.3e+03,'Sample Name' run on 06 October 2015 at 10:33,Raw data stored in - C:\Nu Noble\Results\Data...
1,1.22000,4.1e-04,49700.0,6.0e+01,75600.0,2.0e+02,258000.0,1.6e+02,251000.0,8.7e+02,'Sample Name' run on 06 October 2015 at 10:52,Raw data stored in - C:\Nu Noble\Results\Data...
2,1.22000,5.1e-04,49800.0,5.1e+01,76800.0,1.9e+02,259000.0,1.5e+02,251000.0,9.1e+02,'Sample Name' run on 06 October 2015 at 11:23,Raw data stored in - C:\Nu Noble\Results\Data...
3,0.75800,4.0e-03,49700.0,5.5e+01,66600.0,2.3e+02,258000.0,1.4e+02,144000.0,1.1e+03,'Sample Name' run on 08 October 2015 at 10:13,Raw data stored in - C:\Nu Noble\Results\Data...
4,1.09000,3.6e-04,43300.0,6.3e+01,60800.0,1.7e+02,224000.0,1.3e+02,220000.0,1.4e+03,'Sample Name' run on 08 October 2015 at 10:27,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...
829,1.65538,5.3e-04,55318.2,7.9e+01,307546.0,2.5e+02,298052.0,2.4e+02,347513.0,1.1e+03,'Sample Name' run on 23 June 2020 at 11:02,Raw data stored in - C:\Nu Noble\Results\Data...
830,1.65331,4.3e-04,55167.7,9.0e+01,305585.0,2.2e+02,297394.0,3.0e+02,349141.0,1.3e+03,'Sample Name' run on 24 June 2020 at 09:25,Raw data stored in - C:\Nu Noble\Results\Data...
831,1.65039,4.9e-04,55606.8,8.2e+01,306701.0,2.0e+02,299474.0,2.6e+02,347983.0,1.3e+03,'Sample Name' run on 24 June 2020 at 09:50,Raw data stored in - C:\Nu Noble\Results\Data...
832,1.64847,5.6e-04,55592.8,6.3e+01,306848.0,2.6e+02,299066.0,2.3e+02,346598.0,1.4e+03,'Sample Name' run on 24 June 2020 at 10:08,Raw data stored in - C:\Nu Noble\Results\Data...
833,1.65661,4.7e-04,54386.0,8.5e+01,305470.0,2.8e+02,293720.0,3.3e+02,346964.0,1.2e+03,'Sample Name' run on 29 June 2020 at 09:41,Raw data stored in - C:\Nu Noble\Results\Data...

Il dataframe deve essere filtrato per data, per scegliere la riga di calibrazione d'interesse

In [16]:
# qui si splitta la colonna 'Run' in due colonne con nome del run e data/ora
run_split = airpipette_data['Run'].str.split(" run on ")

In [17]:
# qui di formatta la colonna con nome del run (una Pandas SERIES) e le si da un nome
run_name = run_split.str[0]
run_name = run_name.replace(["'"], [""], regex=True)
run_name.name = 'Run_Name'

In [18]:
# idem per data, inoltre si converte il tipo in datetime64
dataora = run_split.str[1]
dataora.name = 'Date_Time'
dataora = pd.to_datetime(dataora)

In [19]:
# qui si concatenano le nuove serie all'inizio del datframe con dati
airpipette_data = pd.concat([run_name, dataora, airpipette_data], axis = 1)

In [20]:
# qui si elimina la colonna non più usata
airpipette_data.drop('Run',axis=1, inplace=True)
display(airpipette_data)

,Run_Name,Date_Time,40F,err 40F,38IC0,err 38IC0,36IC1,err 36IC1,36IC0,err 36IC0,36F,err 36F,Path
0,Sample Name,2015-10-06 10:33:00,0.73900,4.0e-03,49900.0,5.8e+01,72000.0,2.3e+02,259000.0,1.6e+02,144000.0,1.3e+03,Raw data stored in - C:\Nu Noble\Results\Data...
1,Sample Name,2015-10-06 10:52:00,1.22000,4.1e-04,49700.0,6.0e+01,75600.0,2.0e+02,258000.0,1.6e+02,251000.0,8.7e+02,Raw data stored in - C:\Nu Noble\Results\Data...
2,Sample Name,2015-10-06 11:23:00,1.22000,5.1e-04,49800.0,5.1e+01,76800.0,1.9e+02,259000.0,1.5e+02,251000.0,9.1e+02,Raw data stored in - C:\Nu Noble\Results\Data...
3,Sample Name,2015-10-08 10:13:00,0.75800,4.0e-03,49700.0,5.5e+01,66600.0,2.3e+02,258000.0,1.4e+02,144000.0,1.1e+03,Raw data stored in - C:\Nu Noble\Results\Data...
4,Sample Name,2015-10-08 10:27:00,1.09000,3.6e-04,43300.0,6.3e+01,60800.0,1.7e+02,224000.0,1.3e+02,220000.0,1.4e+03,Raw data stored in - C:\Nu Noble\Results\Data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
829,Sample Name,2020-06-23 11:02:00,1.65538,5.3e-04,55318.2,7.9e+01,307546.0,2.5e+02,298052.0,2.4e+02,347513.0,1.1e+03,Raw data stored in - C:\Nu Noble\Results\Data...
830,Sample Name,2020-06-24 09:25:00,1.65331,4.3e-04,55167.7,9.0e+01,305585.0,2.2e+02,297394.0,3.0e+02,349141.0,1.3e+03,Raw data stored in - C:\Nu Noble\Results\Data...
831,Sample Name,2020-06-24 09:50:00,1.65039,4.9e-04,55606.8,8.2e+01,306701.0,2.0e+02,299474.0,2.6e+02,347983.0,1.3e+03,Raw data stored in - C:\Nu Noble\Results\Data...
832,Sample Name,2020-06-24 10:08:00,1.64847,5.6e-04,55592.8,6.3e+01,306848.0,2.6e+02,299066.0,2.3e+02,346598.0,1.4e+03,Raw data stored in - C:\Nu Noble\Results\Data...
833,Sample Name,2020-06-29 09:41:00,1.65661,4.7e-04,54386.0,8.5e+01,305470.0,2.8e+02,293720.0,3.3e+02,346964.0,1.2e+03,Raw data stored in - C:\Nu Noble\Results\Data...

In [21]:
#qui si filtra il dataframe per data, prendendo una sola riga del dataframe 
import ipywidgets as widgets

data_w = widgets.Dropdown(options=airpipette_data['Date_Time'].to_list(),
                 value=airpipette_data['Date_Time'].to_list()[-1],
                 description='Date_Time of calibration:',
                 disabled=False)
display(data_w)

Dropdown(description='Date_Time of calibration:', index=833, options=(Timestamp('2015-10-06 10:33:00'), Timest…

Select date in the dropdown list BEFORE running the next cell.

In [22]:
print(data_w.value)
airpipette_data_filtered = airpipette_data[airpipette_data['Date_Time'] == data_w.value]

airpipette_data_filtered #calibration_data

2020-06-29 09:41:00

,Run_Name,Date_Time,40F,err 40F,38IC0,err 38IC0,36IC1,err 36IC1,36IC0,err 36IC0,36F,err 36F,Path
833,Sample Name,2020-06-29 09:41:00,1.65661,4.7e-04,54386.0,8.5e+01,305470.0,2.8e+02,293720.0,3.3e+02,346964.0,1.2e+03,Raw data stored in - C:\Nu Noble\Results\Data...

#qui si filtra il dataframe per data, prendendo una sola riga del dataframe 
filter_calibration_min_data = pd.Timestamp(year=2020, month=6, day=23, hour=10)
filter_calibration_max_data = pd.Timestamp(year=2020, month=6, day=23, hour=10, minute = 30)

airpipette_data_filtered = airpipette_data[(airpipette_data['Date_Time'] > filter_calibration_min_data) & \
                                           (airpipette_data['Date_Time'] < filter_calibration_max_data)]

airpipette_data_filtered